apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghtracker-github-app
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secrets # your ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: ghtracker-github-app
    creationPolicy: Owner
  data:
    - secretKey: GHTRACKER_PRIVATE_KEY
      remoteRef:
        key: ghtracker/app_private_key # where you keep the App private key
